"""add unique project name

Revision ID: 2e595fb9a7d2
Revises: 5aebe7f4d5b4
Create Date: 2026-05-30 12:32:25.429864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e595fb9a7d2'
down_revision: Union[str, Sequence[str], None] = '5aebe7f4d5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_projects_name'), 'projects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_projects_name'), 'projects', type_='unique')
    # ### end Alembic commands ###
